name: Build

on: push

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: <Add> msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: <Embedded> git revision
        shell: pwsh
        run: .\Build\embedded-revision.ps1 -Revision ${{ github.sha }} -ProjectFilePath .\Source\Directory.Build.props

      - name: <Build> Plugin
        shell: pwsh
        run: .\FullBuild.ps1

      - name: <Artifact> Plugin
        uses: actions/upload-artifact@v3
        with:
          name: Plugin
          path: |
            Output\*.zip
            Output\update-*.json

  test:

    runs-on: windows-latest

    steps:

      - name: <Checkout> Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: <Add> msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: <Test> Plugin
        shell: pwsh
        run: .\FullTest.ps1

  deploy:
    needs:
      - build
      - test

    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v3

      - name: <Download> Application
        uses: actions/download-artifact@v3
        with:
          name: Plugin
          path: Output

